
# Build settings
remote_theme: pmarsceill/just-the-docs
search_enabled: true
plugins:
  - jekyll-feed

title: WavesPolska
tagline: "Dokumentacja WavesPolska"
description: "Materiałt edukacyjne na temat technologii Waves"
type: website